/**************************************************************/
/* Automatically generated by './mkconfig.sh'.  Do note edit! */
/**************************************************************/
#define YALS_OS "Darwin GS19081.SP.CS.CMU.EDU 20.6.0 x86_64"
#define YALS_COMPILED "Tue Dec  7 17:16:30 EST 2021"
#define YALS_RELEASED "Mi 24. Jun 19:01:51 CEST 2020"
#define YALS_VERSION "044"
#define YALS_ID "34f730fabec286764b3a9f079130cc0a29c2dc47"
