#!/bin/sh

die () {
   echo "*** mkconfig: $*" 1>&2
   exit 1
}

[ -f makefile ] || die "can not find 'makefile'"

cat<<EOF
/**************************************************************/
/* Automatically generated by './mkconfig.sh'.  Do note edit! */
/**************************************************************/
EOF

echo "#define YALS_OS \"`uname -srmn`\""
echo "#define YALS_COMPILED \"`date`\""
echo "#define YALS_RELEASED \"Mi 24. Jun 19:01:51 CEST 2020\""
echo "#define YALS_VERSION \"044\""
echo "#define YALS_ID \"34f730fabec286764b3a9f079130cc0a29c2dc47\""
