/**************************************************************/
/* Automatically generated by './mkconfig.sh'.  Do note edit! */
/**************************************************************/
#define YALS_OS "Linux napolco 4.9.0-8-amd64 x86_64"
#define YALS_COMPILED "Tue Nov 30 00:05:08 UTC 2021"
#define YALS_RELEASED "Fr 1. Mär 05:17:48 CET 2019"
#define YALS_VERSION "03v"
#define YALS_ID "b1316746d40f72f147cde3f4ec54fadbe0730427"
