/**************************************************************/
/* Automatically generated by './mkconfig.sh'.  Do note edit! */
/**************************************************************/
#define YALS_OS "Darwin GS19081.SP.CS.CMU.EDU 20.6.0 x86_64"
#define YALS_COMPILED "Wed Nov 17 10:03:49 EST 2021"
#define YALS_RELEASED "Fr 1. Mär 05:17:48 CET 2019"
#define YALS_VERSION "03v"
#define YALS_ID "b1316746d40f72f147cde3f4ec54fadbe0730427"
